// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CamControl","status":true,"description":"Allows greater control over where the game camera is focused. View HELP for plugin commands.","parameters":{"Tile Size":"48"}}
];
